### ISSUE TITLE
Make it easier to create secrets for local deployment

### ISSUE THREAD

**Issue by csomh** [packit-service/deployment#72]
Documentation for how to create secrets for a local deployment is missing. 

We know that want to have similar steps to [the ones taken](https://github.com/packit-service/packit-service/blob/master/files/deployment.yaml#L32) when setting up an env in CI (thanks @TomasTomecek!).

Ideally we should try to factor out those tasks in a playbook in this repo, and create a `make`-target, which would run this playbook, and create all the secrets needed for a local deployment.

Also update the README documenting the above.

**Comment by TomasTomecek** [comment]
Bonus points: turn it into an ansible role :)

**Comment by rishavanand** [comment]
Can I take this up? I'm already trying to get the packit-service to work on my system. Will document along the way.

**Comment by csomh** [comment]
sure @rishavanand, it's all yours :)
